<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Paradox Descriptor</string>
	<key>scopeName</key>
	<string>source.paradox-mod</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tags-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#version-value</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path-value</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#known-key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unknown-key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#braces</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.paradox-mod</string>
			<key>match</key>
			<string>#.*$</string>
		</dict>
		<key>tags-block</key>
		<dict>
			<key>comment</key>
			<string>tags/dependencies = { "..." "..." } - entries colored as tags</string>
			<key>begin</key>
			<string>\b(tags|dependencies)\s*(=)\s*(\{)</string>
			<key>end</key>
			<string>\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.property-name.paradox-mod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.paradox-mod</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.paradox-mod</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.paradox-mod</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.paradox-mod</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.tag.paradox-mod</string>
							<key>match</key>
							<string>[^"]+</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>version-value</key>
		<dict>
			<key>comment</key>
			<string>version numbers get numeric coloring so they stand out from names</string>
			<key>match</key>
			<string>\b(version|supported_version|remote_file_id)\s*(=)\s*(")([^"]*)(")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.property-name.paradox-mod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.paradox-mod</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.paradox-mod</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.version.paradox-mod</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.paradox-mod</string>
				</dict>
			</dict>
		</dict>
		<key>path-value</key>
		<dict>
			<key>match</key>
			<string>\b(path|picture|replace_path)\s*(=)\s*("[^"]*")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.property-name.paradox-mod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.paradox-mod</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.path.paradox-mod</string>
				</dict>
			</dict>
		</dict>
		<key>known-key</key>
		<dict>
			<key>name</key>
			<string>support.type.property-name.paradox-mod</string>
			<key>match</key>
			<string>\b(name|version|supported_version|path|remote_file_id|picture|tags|replace_path|dependencies)\s*(?==)</string>
		</dict>
		<key>unknown-key</key>
		<dict>
			<key>name</key>
			<string>variable.other.property.paradox-mod</string>
			<key>match</key>
			<string>\b[A-Za-z_][A-Za-z0-9_]*\s*(?==)</string>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.paradox-mod</string>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.paradox-mod</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.paradox-mod</string>
			<key>match</key>
			<string>=</string>
		</dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.paradox-mod</string>
					<key>match</key>
					<string>\{</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.paradox-mod</string>
					<key>match</key>
					<string>\}</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
